name: Publish DEV

on:
  push:
    branches:
      - "develop"

jobs:
  publish:
    uses: './.github/workflows/publish.yml'
    with:
      tag: edge
      version_script: |
        const { findSourceAndTargetBranches } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/branch.utils.mjs`);
        const {
          determineNextDevVersion,
          stringifyVersion,
        } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/version.utils.mjs`);
        
        const [source, target] = await findSourceAndTargetBranches(context);
        const nextVersion = await determineNextDevVersion(source);
        
        return stringifyVersion(nextVersion);
