name: Publish Release Candidate

on:
  push:
    branches:
      - 'main'

jobs:
  tag_rc_image_app:
    name: tag rc image app
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Pull docker image
        run: docker pull ${{ vars.BASE_IMAGE_NAME }}-app:edge

      - name: Tag docker image
        run: docker tag ${{ vars.BASE_IMAGE_NAME }}-app:edge ${{ vars.BASE_IMAGE_NAME }}-app:release-candidate

      - name: Push docker image
        run: docker push ${{ vars.BASE_IMAGE_NAME }}-app:release-candidate

  tag_rc_image_api:
    name: tag rc image api
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Pull docker image
        run: docker pull ${{ vars.BASE_IMAGE_NAME }}-api:edge

      - name: Tag docker image
        run: docker tag ${{ vars.BASE_IMAGE_NAME }}-api:edge ${{ vars.BASE_IMAGE_NAME }}-api:release-candidate

      - name: Push docker image
        run: docker push ${{ vars.BASE_IMAGE_NAME }}-api:release-candidate

  tag_rc_commit:
    name: 'tag rc commit'
    needs:
      - tag_rc_image_app
      - tag_rc_image_api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: tag release-candidate
        uses: ./.github/actions/tag-commit
        with:
          TAG_NAME: release-candidate

      # We also change the edge tag, as this workflow is most likely triggered by a merge commit,
      # which means that release-candidate would be one commit ahead of edge.
      # Re-tagging edge fixes that.
      # Note that we do not rebuild the Docker image, as we can expect the merge commit to never modify any behaviour.
      - name: tag edge
        uses: ./.github/actions/tag-commit
        with:
          TAG_NAME: edge
