name: Publish INT

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    uses: './.github/workflows/publish.yml'
    with:
      tag: release-candidate
      version_script: |
        const { findSourceAndTargetBranches } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/branch.utils.mjs`);
        const {
        determineNextRcVersionBySourceBranch,
        stringifyVersion,
        } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/version.utils.mjs`);
        
        const [source, target] = await findSourceAndTargetBranches(context);
        const nextVersion = await determineNextRcVersionBySourceBranch(source);
        
        return stringifyVersion(nextVersion);
